repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length, 119]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--max-line-length, 119, --ignore, E203, E402, W503, W504]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile, black]